### ISSUE TITLE
GetAuthResponse.Item is missing

### ISSUE THREAD

**Issue by ddicato** [plaid/plaid-go#118]
When calling the /auth/get endpoint, the raw JSON response contains an "item" field. But when we use GetAuth or GetAuthWithOptions, this field is not incorporated into the GetAuthResponse. This requires us to make an unnecessary call into GetItem for additional item metadata.

This is inconsistent with e.g. GetAccountsResponse, which contains the `Item` field as expected.

**Comment by cgfarmer4** [comment]
@ddicato looks like the issue is resolved aforementioned in the mentioned PR. Please reopen if you have further issues.
