### ISSUE TITLE
Missing support for /sandbox/item/fire_webhook 

### ISSUE THREAD

**Issue by phoenixy1** [plaid/plaid-go#121]
Hi team!

It appears that we are missing a function for the /sandbox/item/fire_webhook endpoint in this clib?

**Comment by stevemkrause** [comment]
Hi there,

Thanks for reaching out! Our Go library natively supports all Plaid endpoints, including `sandbox/item/fire_webhook`. If you are attempting to call this endpoint and receiving errors, please follow up with a `request_id`, or file an issue under [the Webhook Functionality section of the Plaid Support dashboard](https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/webhook).

I hope this helps. Please feel free to reach back out if you need further assistance, or mark this issue as Closed is you're all set!

**Comment by cgfarmer4** [comment]
@phoenixy1 can we close this out or are you still having issues?

**Comment by cgfarmer4** [comment]
@phoenixy1 Please reopen if you are still having issues.

**Comment by phoenixy1** [comment]
So yeah, I really can't find the method for this -- if it exists in the library can someone tell me what the method is called?  I searched for both "sandbox" and "webhook" and nothing matching came up.

**Comment by phoenixy1** [comment]
(Note that I only need this for documentation purposes, so if we decide we're going to fix this with generated clibs instead, that is fine and we can close the task.)
