### ISSUE TITLE
GetInstitutionsOptions is Missing Routing Number Option

### ISSUE THREAD

**Issue by KerryAlsace** [plaid/plaid-go#132]
The `institutions/get` endpoint allows a set of optional parameters, and one of those options is [`"routing_numbers"`](plaid.com/docs/#retrieve-all-institutions-request). However, RoutingNumbers is not included in the [GetInstitutionsOptions](https://godoc.org/github.com/plaid/plaid-go/plaid#GetInstitutionsOptions) struct, so filtering results by routing numbers is unavailable in the Go library.

**Comment by cgfarmer4** [comment]
hi @KerryAlsace- Thanks for the report. Will look into getting this added.
