### ISSUE TITLE
Align repo with Go best practices and idioms

### ISSUE THREAD

**Issue by DerekDuchesne** [plaid/plaid-go#160]
My team and I think that this repo would benefit a lot from some small improvements that better align it with Go best practices and idioms. These changes already have issues corresponding to them, but there seems to be little activity.

- Using Go modules (mentioned in #71)
- Including a context in all API calls (mentioned in #71 and initial implementation provided in PR #84)
- Using pointers for nullable fields (mentioned in #113)

These issues haven't gotten responses in months and we were wondering about the overall status of this repository.

My team is willing to spend some developer resources implementing these, but we want to make sure that this project is still active and is open to accepting such changes. Outstanding PRs implementing some of the above were never merged.

Thanks,

/cc @skylarmb @pbernasconi @aeidelson

Resources from the official Go team on Go best practices:
	- https://blog.golang.org/using-go-modules
        - https://blog.golang.org/context

**Comment by skylarmb** [comment]
hi there @DerekDuchesne, we are moving very soon to auto-generating this `plaid-go` library from our [OpenAPI spec](https://github.com/plaid/plaid-OpenAPI) using [swagger-codegen](https://swagger.io/tools/swagger-codegen/). This will be an entirely new version of `plaid-go`. I do not know if this will solve all your concerns here, but I will check with the people working on that and let you know.

**Comment by DerekDuchesne** [comment]
We're very happy to hear that this project is moving to a generated approach! Thank you for providing this!

The generated code would fix the context and pointer issues mentioned above, however updating the repository to use modules would have to be done separately. In a recent Go [blog post](https://blog.golang.org/go1.16), it was mentioned that 96% of Go developers now use modules, so I can't stress enough that it would be a major benefit to use modules in the revamped version of `plaid-go`. The upgrade to modules should follow the [best practices](https://blog.golang.org/using-go-modules) including semantic versioning, tagging releases, etc.

One note about the codegen project -  you said that you're using `swagger-codegen`. From our experience with code generators for Go, we found `swagger-codegen` is not as Go-friendly as other projects. We've found better luck with [go-swagger](https://github.com/go-swagger/go-swagger#how-is-this-different-from-go-generator-in-swagger-codegen), which was specifically built with Go in mind.

**Comment by DerekDuchesne** [comment]
The Plaid OpenAPI spec repository mentions using openapi-generator (not swagger-codegen) which I believe started as a fork of the former and has since improved its Go implementation (cannot comment on how well though) - which should support OpenAPI v3 that Plaid's OpenAPI spec uses. In light of that, my previous comment about `go-swagger` is probably not relevant. `go-swagger`  only supports OpenAPI v2.

**Comment by gganley** [comment]
Any idea on when this transition will occur?

**Comment by cgfarmer4** [comment]
Hi @DerekDuchesne and @gganley- We don't have a date set in stone at the moment but we anticipate the beginning of Q3 at the latest. We have some examples for generating other languages on our `plaid-OpenAPI` [repo](https://github.com/plaid/plaid-OpenAPI) and I would encourage trying that out for `go` in the meantime. The command would be something like:

```
openapi-generator-cli generate -g go \
-i 2020-09-14.yml \
-o generated-go \
-p packageName=plaid
```

The option `isGoSubmodule` [you can pass here](https://openapi-generator.tech/docs/generators/go/) seem to indicate you can generate as a module. Hope that helps!

**Comment by mickeyreiss** [comment]
I would prefer a non-breaking upgrade that adds context-aware methods. This would be a similar approach to the go standard libraries, such as `http.NewRequestWithContext`. This way, we could incrementally adopt the context aware methods as needed.

**Comment by nc-wittj** [comment]
@cgfarmer4 Looks like we're less than a month out before this library goes into maintenance only mode. Any update on the beta that is "coming soon"?

> After 8/16/21, this major version of the library will only receive critical security patches. We are planning on releasing a generated beta soon.

**Comment by cgfarmer4** [comment]
hi @nc-wittj we are iterating on the new version right now and it will ship before entering maintenance mode.
