### ISSUE TITLE
GetBalancesWithOptions doesn't include the option that really matters

### ISSUE THREAD

**Issue by jcorry** [plaid/plaid-go#166]
I am happy to submit a PR that fixes this issue, I just wanted to surface it here first before doing the work in case it is unwanted (don't want to waste anyone's time).

`*Client.GetBalancesWithOptions` uses a `getBalanceRequest` type to submit the request to the Plaid service. The request does not include a field for`MinLastUpdatedDatetime`, which is a required option (🤔) for the Capital One institution: https://plaid.com/docs/api/products/#accountsbalanceget

Without that field, requests for account holders at Capital One fail and return `INVALID_FIELD`.

The request struct needs to be modified to include that field.

I had to write my own implementation of `plaid.Client` in order to make this request.

Shall I prepare a PR that fixes this?

**Comment by phoenixy1** [comment]
@jcorry thank you for the offer to help!  This should be fixed as of 7.2.0.
