### ISSUE TITLE
Account SubType "fixed annuity" is missing

### ISSUE THREAD

**Issue by nc-wittj** [plaid/plaid-go#191]
`fixed annuity` appears [in the API docs](https://plaid.com/docs/api/accounts/#StandaloneAccountType-fixed%20annuity_investment), and [in the schema](https://github.com/plaid/plaid-openapi/blob/84a303ae4a48816951233ba0db0ce24c7e633c9d/2020-09-14.yml#L9968-L9970). However, it seems to be missing from the [list of AccountSubtype constants](https://github.com/plaid/plaid-go/blob/master/plaid/model_account_subtype.go) in this package.

**Comment by phoenixy1** [comment]
next clib release is out, this should now be fixed
