### ISSUE TITLE
Not an issue - but maybe you can help.... pClient.CreateLinkToken

### ISSUE THREAD

**Issue by johndpope** [plaid/plaid-go#195]
I got a repo that's dependency is on 
pClient.CreateLinkToken

https://github.com/connorbenton/fin/issues/18

Is there a way around this? Is there some documentation on breaking changes? how to get around?? thanks in advance

**Comment by johndpope** [comment]
did some digging and have made some progress. I have issues with this documentation - will submit new tickets.

**Comment by johndpope** [comment]
This is a breaking change - and should be documented somewhere

<img width="827" alt="Screen Shot 2021-08-31 at 10 27 34 am" src="https://user-images.githubusercontent.com/289994/131422584-b44cff32-15af-44a2-87f1-428a01389f53.png">

**Comment by phoenixy1** [comment]
Yep, the Go client libraries did have a release with breaking changes 11 days ago. You can see that the version numbering scheme restarted: https://github.com/plaid/plaid-go/releases. If you need to use a release that is compatible with the old client libraries, we recommend 7.3.0. I've submitted a PR to clarify this situation in the README.

**Comment by johndpope** [comment]
Thanks Alex
