### ISSUE TITLE
Clarification on running templates.

### ISSUE THREAD

**Issue by johndpope** [plaid/plaid-go#196]
I'm a golang beginner - what's this moustache file? Is that the canonical way to create client? How to run

**Comment by phoenixy1** [comment]
I believe the moustache files are used as part of the process of generating the Go client library from the OpenAPI specification and that you do not need to use them as a consumer of the library.

See the Plaid Quickstart (https://github.com/plaid/quickstart) for an example of how to use the Go client library with Plaid.
