### ISSUE TITLE
SignalEvaluate should use SignalEvaluateRequest

### ISSUE THREAD

**Issue by sgtmacdiesel** [plaid/plaid-go#206]
https://github.com/plaid/plaid-go/blob/690d222aca3a6ce6a21674a88c673ec7e911b4d0/plaid/api_plaid.go#L12787

Hello, SignalEvaluate should use SignalEvaluateRequest it seems. I'm currently attempting to integrate SignalEvaluate into our API however this specific request is currently using RequestBody. Should I just use key:value in the `map[string]map[string]interface{}` that it is currently set to?

**Comment by stephenjayakar** [comment]
Hey @sgtmacdiesel! We just released plaid-go `v1.4.0` -- this should fix this to use the request body.

**Comment by sgtmacdiesel** [comment]
Great @stephenjayakar thank you very much for the update!

**Comment by sgtmacdiesel** [comment]
Hey @stephenjayakar one quick question about this endpoint, it always returns a 400 for me in Sandbox env. Is that expected?
