### ISSUE TITLE
Missing `pension` AccountSubtype constant

### ISSUE THREAD

**Issue by nc-wittj** [plaid/plaid-go#231]
Now that `float64` is used for numbers, I'm currently working on upgrading from the V1 SDK in our app. 

Requesting a link token allows specifying a set of [account_filters based on the Account subtype](https://plaid.com/docs/api/tokens/#link-token-get-response-metadata-account-filters). One of the options we've been using is `pension`. However, there's no constant for this account subtype. I do see a `person` subtype on that page and as a constant, which I accidentally initially used, but that results in a very confusing error message from the API. (It would be helpful for that error message to say what type was incorrect.) My guess is `person` is a typo, and is supposed to be `pension`, which is listed on the [account schema page](https://plaid.com/docs/api/accounts/#StandaloneAccountType-investment-pension), and seems to work correctly with the API.

**Comment by phoenixy1** [comment]
Oh gosh how embarrassing. Thank you for the report, I have a PR in progress to fix this. Do you need it urgently or is it ok if we wait until the next scheduled release of the SDK (early April)?

**Comment by nc-wittj** [comment]
I currently have it hardcoded, so probably not a huge rush.

**Comment by phoenixy1** [comment]
this should now be fixed in the latest client library version.
