### ISSUE TITLE
Missing `identity_verification` in allowed products for link token creation

### ISSUE THREAD

**Issue by davemilller** [plaid/plaid-go#246]
Hi, my team is currently integrating with Plaid for identity verification as well as some other use cases. While following [this](https://plaid.com/docs/identity-verification/) guide for ID verification with Link, we realized that the Go SDK was missing both the `identity_verification.template_id` field on the `/link/token/create` request as well as `identity_verification` in allowed products. We reached out about a week ago and the `identity_verification.template_id` was added (the next day, great turnaround!) but we are still missing `identity_verification` in the [allowed products](https://github.com/plaid/plaid-go/blob/master/plaid/model_products.go#L22) so we still cannot craft the request using the SDK. I currently have a workaround so this is not terribly important, but I thought I would bring it to attention.

**Comment by phoenixy1** [comment]
Fixed in currently outgoing release; closing
