### ISSUE TITLE
InstitutionsGetByIdResponse doesn't appear set by InstitutionsGetByIdRequest 

### ISSUE THREAD

**Issue by benjwg** [plaid/plaid-go#269]
I have some very simple code that is not behaving as I would expect:

```
request := plaid.NewInstitutionsGetByIdRequest(institutionID, []plaid.CountryCode{plaid.COUNTRYCODE_US})
request.SetOptions(plaid.InstitutionsGetByIdRequestOptions{IncludeOptionalMetadata: plaid.PtrBool(true)})

resp, _, err := c.getPlaidService().InstitutionsGetById(pctx).InstitutionsGetByIdRequest(*request).Execute()
if err != nil {
    return nil, errors.New("error fetching institution details")
}

institution := resp.GetInstitution()
```

There is no err returned from the method, but none of the fields on `institution` are set.

If I set `debug` to `true` for the client the dump includes all the institution details as I would expect, so the api call is working.
Same thing if I actually return the `http.Response` from the method and print it, it contains all the expected details.

Even stranger, if I instead use `institution, ok := resp.GetInstitutionOK()` `ok` is `true`, but `institution` remains unset.

I can't imagine what I could be doing wrong, but I also would be surprised a bug like this would have gotten through - can anyone reproduce and/or advise?

**Comment by phoenixy1** [comment]
@benjwg you don't happen to be running this code based on the Quickstart, by any chance? The Quickstart uses an old version of the go client library that has a bug in it that would cause this behavior. Can you make sure that you're using the latest version of the go client library and see if the issue still reproduces?

**Comment by benjwg** [comment]
Yep, was a version problem, thanks very much
