### ISSUE TITLE
Stop generating the client?

### ISSUE THREAD

**Issue by dustinevan** [plaid/plaid-go#275]
It's easier for me to write my own client from the HTTP docs than it is to read this go client and figure out how to use it.

**Comment by phoenixy1** [comment]
If you'd like to write your own version of a Go client library for Plaid, we can absolutely link to it as a community library! Check out https://github.com/plaid/plaid-openapi  as a resource. Once your client is built feel free to open an issue here to let us know about it. We don't currently have any plans to stop generating the official Go client.

**Comment by dustinevan** [comment]
I'm actually doing this, but probably just the routes I need. Really this issue was created out of frustration, before I realized that my complaint belonged with the OpenAPI go generator haha. 

Also, thanks for the go examples in the API docs.
