### ISSUE TITLE
Use interface over GenericOpenAPIError to read PlaidError

### ISSUE THREAD

**Issue by AlexCuse** [plaid/plaid-go#279]
Conveying `PlaidError` through the internals of `OpenAPIError` makes it hard to setup plaid error returns in tests.  Using an interface would make it easy for user-defined types to convey specific `PlaidError` details to code under test (eg to test handling of the `PRODUCT_NOT_READY` error code received in an auth response).

**Comment by AlexCuse** [comment]
I will open a PR for this tomorrow after running a few more tests.

**Comment by AlexCuse** [comment]
I like the approach of a helper function mentioned in the PR better to be honest - I was trying to use as light a touch as possible since I don't know what the codegen side well but it's way more convenient that way.  I can't update the issue name but changing it to something general about better support for PlaidError under test it might be appropriate.  Thanks for such a quick response @aarohmankad

**Comment by aarohmankad** [comment]
The helper function from #280 was merged in our latest release: #282
