### ISSUE TITLE
Exported functions return unexported types

### ISSUE THREAD

**Issue by anoopr** [plaid/plaid-go#28]
This seems unusual to me. Is there a reason for this? For example ConnectAddUser returns a pointer to postResponse. I can't pass that type down from the function I call ConnectAddUser from.

**Comment by michaelckelly** [comment]
@anoopr - Thanks for the feedback. You're right, we should consider changing all exported functions to return exported types. We're happy to review a pull request that introduces this change, otherwise we'll put it on our backlog!

**Comment by ns-cweber** [comment]
Also worth noting that a fair number of these are just structs around a string mfaQuestion{Question string}, mfaDevice{Message string}, etc. Also, mfaList's name is confusing in that it's actually used as a list element (an mfaResponse contains a `List []mfaList` field).
