### ISSUE TITLE
cannot install the package

### ISSUE THREAD

**Issue by vladyslav2** [plaid/plaid-go#294]
Hello
For some reason I cannot run the package at all.

here what I do
```bash
# go mod init ...
# go get github.com/plaid/plaid-go/v20   
# go run main.go
tries to download plaid-go and fails with:
github.com/myproject/kyc-api/internal/adapters/kyc/plaidkc imports
        github.com/plaid/plaid-go: cannot find module providing package github.com/plaid/plaid-go
```

tried both `import "github.com/plaid/plaid-go/v20"` and `import plaid "github.com/plaid/plaid-go"`
after reading a lot of articles I feel like like problem in the package itself

**Comment by phoenixy1** [comment]
Hmm, I was not able to reproduce this. I tried the following (for my main.go file I used the server.go file in the quickstart but updated the go version to 20.)

```
go mod init my-test-project
go get github.com/plaid/plaid-go/v20
go run main.go
```


and it worked fine (after installing the remaining deps when being prompted to after running main.go) I'm not aware of other folks having issues with this either.

**Comment by phoenixy1** [comment]
@vladyslav2 thank you for uploading that repo, that was very helpful in diagnosing the issue! I think the problem is that your import statement is this:

```
	plaid "github.com/plaid/plaid-go/v20/"
```

and I believe it needs to look like this:

```
	plaid "github.com/plaid/plaid-go/v20/plaid"
```

**Comment by vladyslav2** [comment]
@phoenixy1 my pleasure.

I just had a thought, maybe we should expend the repo and create for you a end-to-end example?

**Comment by phoenixy1** [comment]
@vladyslav2 there is an end-to-end example in the Quickstart: https://github.com/plaid/quickstart
If there's something else you had in mind to add, let me know!

**Comment by vladyslav2** [comment]
@phoenixy1  I mean, we can pull togegher and example on golang so people like me will be able to see whole working example rigth away. And if they are doing something incorrectly they will be able to compare the code

**Comment by phoenixy1** [comment]
@vladyslav2 right, I think the Go example in the Quickstart is supposed to do that: https://github.com/plaid/quickstart/blob/master/go/server.go

Is there something else you were thinking of? Or do you think maybe the example should be linked from the Readme?
