### ISSUE TITLE
Why is this marked as "Legacy" on the plaid site

### ISSUE THREAD

**Issue by autoferrit** [plaid/plaid-go#38]
I was wondering why plaid-go was marked as a legacy library on the plaid website here

https://plaid.com/docs/resources/#legacy-libraries

When there is no modern option like others, and the Readme doesn't mention this. Is there a better option to use?

**Comment by cloudmode** [comment]
I figured out why it's marked legacy, the api has changed completely (for example there is no Sandbox environment) and this library has not been upgraded. Thus, 'legacy'. Note that there are also node, python and ruby legacy libraries. Nobody's gotten around to upgrading this on. So, fork it is.....

**Comment by autoferrit** [comment]
Yea, i am playing with this fork

https://github.com/Wearevest/plaidgo 

with a commit or two pulled from @alphaspark 

I would like to see these changes merged in though.

**Comment by michaelckelly** [comment]
@autoferrit @cloudmode - Better late than never, wanted to let you know that `plaid-go` is an officially supported library again and is now up-to-date with our current API (released as `1.x.x`)!
