### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by cbelsole** [plaid/plaid-go#47]
1. Tests are not running on https://github.com/plaid/plaid-go/pull/46 automatically. 
2. When you are on circle you get a message that the repo should be upgraded to v2 even when the config is using v2.
3. It looks like the build is broken due to `API keys are not enabled for the Dwolla ACH integration`. 

```
--- FAIL: TestCreateDwollaToken (8.71s)
	require.go:765: 
			Error Trace:	processor_test.go:47
			Error:      	Expected nil, but got: plaid.Error{APIResponse:plaid.APIResponse{RequestID:"zCtjM"}, ErrorType:"INVALID_INPUT", ErrorCode:"INVALID_PRODUCT", ErrorMessage:"the provided API keys are not enabled for the Dwolla ACH integration. please see https://plaid.com/docs/link/dwolla/ for more information", DisplayMessage:"", StatusCode:400}
			Test:       	TestCreateDwollaToken
```

**Comment by pbernasconi** [comment]
Hey @cbelsole – hope you found a resolution to your issues.

I'm going to close this as stale and an issue with your developer keys. Please [contact our Support team](https://dashboard.plaid.com/support/new) if you need help getting enabled for the Dwolla ACH integration

**Comment by cbelsole** [comment]
We wrote our own client to interface with Plaid as we were unsure whether this was officially supported or not. I see it's now listed on the official libraries page (https://plaid.com/docs/libraries/). I guess it might be worth looking into if we need greater functionality, but at the moment we are running with ours.

**Comment by pbernasconi** [comment]
Gotcha - helpful to know! We're working to improve our client-library support and documentation, so if you feel the urge to switch over to the officially supported library please do!
