### ISSUE TITLE
include_display_data in GetInstitutionByID

### ISSUE THREAD

**Issue by colinking** [plaid/plaid-go#50]
It looks like the `InstitutationsByID` endpoint does not support fetching display data. Though, I noticed that the `include_display_data` [isn't documented](https://plaid.com/docs/#all-institutions), so I assume it exists just for Plaid Link.

Would there be interest in surfacing this option in `plaid-go`? If so, I'd be happy to submit a PR.

**Comment by tanatplaid** [comment]
I've included this as part of #56 (thanks @jordanabderrachid for some of the initial work!)

**Comment by pbernasconi** [comment]
Closing this – logos and colors are now available via a [different options parameter](https://github.com/plaid/plaid-go/blob/master/plaid/institutions.go#L18)

Please see the https://plaid.com/docs/#institution-search-request docs for details!

**Comment by rubens21** [comment]
@pbernasconi , 

At least in sandbox, the parameter `include_optional_metadata` does not bring the display data (logo and colors).

That parameter works for get and search endpoints, but only `include_display_data` option work on the `InstitutationsByID`.

I tested using Postman on sandbox, so not related to the Go package. I am only posting here to contribute to the thread.

**Comment by tylerkatz** [comment]
> At least in sandbox, the parameter `include_optional_metadata` does not bring the display data (logo and colors).
> 

Seems this has been fixed and logo now does come back with `include_optional_metadata`
