### ISSUE TITLE
Incorrect EFT Schema

### ISSUE THREAD

**Issue by george-e-shaw-iv** [plaid/plaid-go#63]
The schema used for EFT is the same schema used for ACH, which is wrong. As per the [documentation](plaid.com/docs/#ach-numbers-schema), ACH has the following fields:

- `account_id`
- `account`
- `routing`
- `wire_routing`

and EFT has the following fields:

- `account_id`
- `account`
- `institution`
- `branch`

But with the current schema in this SDK they both use the ACH fields, which is the [`AccountNumber`](https://github.com/plaid/plaid-go/blob/master/plaid/accounts.go#L26) type.

**Comment by pbernasconi** [comment]
Thanks for flagging this @george-e-shaw-iv – I'm working on a fix today, and will push it up by EOD!
