### ISSUE TITLE
No Transactions Exist in Sandbox Fixtures for 2016-01-01 to 2017-01-01

### ISSUE THREAD

**Issue by george-e-shaw-iv** [plaid/plaid-go#67]
The date range of `2016-01-01` to `2017-01-01` is used in the `transactions_test.go` file, but no transactions exist in that date range. The `transactions` key comes back `null` and the `total_transactions` key comes back as `0`.

**Comment by davidzhanghp** [comment]
Hi @george-e-shaw-iv ,

The test has changed in the meantime to not use those hard coded dates anymore. The tests now will always use time ranges that have transactions.

Thank you so much for reporting this!
