### ISSUE TITLE
Unmarshaling Directly from Response Body Buffer

### ISSUE THREAD

**Issue by george-e-shaw-iv** [plaid/plaid-go#70]
In `*Client.do` the response body is read and the bytes are then used to unmarshal into the proper data type. An unnecessary extra step is being done by dumping the contents of the buffer. The buffer can be read from and unmarshaled directly without needing to dump the contents using the following pattern:

```
if err := json.NewDecoder(res.Body).Decode(v); err != nil {
```

Just for clarification, the function would go from its current implementation to this:

```go
// do is used by Call to execute an http.Request and parse its response.
// Also handles parsing of the plaid error format.
func (c *Client) do(req *http.Request, v interface{}) error {
	res, err := c.httpClient.Do(req)

	if err != nil {
		return err
	}
	defer res.Body.Close()

	// Successful response
	if res.StatusCode == 200 {
		return json.NewDecoder(res.Body).Decode(v)
	}

	// Attempt to unmarshal into Plaid error format
	var plaidErr Error
	if err =json.NewDecoder(res.Body).Decode(&plaidErr); err != nil {
		return err
	}
	plaidErr.StatusCode = res.StatusCode
	return plaidErr
}
```

**Comment by davidzhanghp** [comment]
Hi George,

Really appreciate your feedback on this one.

Addressed in https://github.com/plaid/plaid-go/pull/112/files
