### ISSUE TITLE
Status missing from GetItemResponse

### ISSUE THREAD

**Issue by someone1** [plaid/plaid-go#73]
See https://plaid.com/docs/#retrieve-item

The `Status` object is missing in https://godoc.org/github.com/plaid/plaid-go/plaid#Item

**Comment by DerekDuchesne** [comment]
@maxdjohnson @pbernasconi 

Hello,
I ran into a situation with my development team where we need this missing field. Would it be possible for someone to review my pull request and merge it in?
Thank you!

**Comment by aww-quovo** [comment]
@someone1 this should be fixed by #92

**Comment by someone1** [comment]
@aww-quovo - please see [my comment](https://github.com/plaid/plaid-go/pull/92#issuecomment-576671534). I appreciate your attempt at addressing this but it doesn't actually do so correctly.

**Comment by jacksiegel** [comment]
@someone1 this should be fixed by #93.
