### ISSUE TITLE
Sandbox institutions return non-deterministic results

### ISSUE THREAD

**Issue by DerekDuchesne** [plaid/plaid-go#86]
We've been trying to write integration tests against this library, but particularly for `GetInstitutionByIDWithOptions` and `GetTransactionsWithOptions`, we notice that the calls can return varying results.

For `GetInstitutionByIDWithOptions`, we've noticed that the `InstitutionStatus` can be null. This is actually an issue for this library itself, since one of the tests expects this to always be defined. See: https://github.com/plaid/plaid-go/blob/master/plaid/institutions_test.go#L77. The test isn't failing at the time of writing this issue, but I've seen it happen in the past. Example: https://circleci.com/gh/plaid/plaid-go/123?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

For `GetTransactionsWithOptions`, we've noticed that the number of transactions can vary over time, which makes testing for a specific number of results impossible.

Do you have any recommendations for dealing with varying Sandbox API results? We've read the section on integration testing, but we're already using the sandbox-only institutions like the tests in this library.

**Comment by davidzhanghp** [comment]
hi, @DerekDuchesne, 

re: InstitutionStatus
we have addressed this recently. The following institutions should have fixed status.
ins_109508
ins_109512

re: GetTransactionsWithOptions, given the same account with the same dates, the transactions should not change.

Please file a support ticket if you notice this issue with `GetTransactionsWithOptions`. Someone will take a look.

Thanks,
David
